sudo: required
dist: trusty

os:
  - windows
  - linux
  - osx

language: node_js
node_js:
  - 8
  - 10
  - 11

dist: trusty
sudo: false

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - yarn

script:
  - yarn ci:pipelines
